name: minecraft_cube_desktop
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.2

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  archive: ^3.1.2
  path: ^1.8.0
  file: ^6.1.2
  intl: ^0.17.0
  formz: ^0.4.0
  dio: ^4.0.0
  process:
    git: 
      url: https://github.com/Tokenyet/process.dart.git
      ref: 9a9b873604a0c8f58d1419e160146885fd8392b6
  rxdart: ^0.27.3
  collection: ^1.15.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  json_annotation: ^4.1.0

  # widgets
  dropdown_button2: ^1.1.1
  flutter_typeahead: ^3.2.4
  # overlay_builder: ^1.1.0
  # flutter_portal: ^0.4.0
  group_button: ^4.6.0
  badges: ^2.0.2
  flutter_markdown: ^0.6.9+1


  flutter_localizations:
    sdk: flutter

  i18n_extension: ^4.1.0

  # windows
  desktop_window: ^0.4.0
  platform: ^3.1.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 03d957e8b5c99fc83cd4a781031b154ab3de8753
  url_launcher: ^6.0.20

  #project
  app_updater_repository:
    path: ./packages/app_updater_repository
  console_repository:
    path: ./packages/console_repository
  cube_api:
    path: ./packages/cube_api
  cube_properties_repository:
    path: ./packages/cube_properties_repository
  duplicate_cleaner_repository:
    path: ./packages/duplicate_cleaner_repository
  eula_stage_repository:
    path: ./packages/eula_stage_repository
  forge_installer_repository:
    path: ./packages/forge_installer_repository
  installer_creator_repository:
    path: ./packages/installer_creator_repository
  installer_repository:
    path: ./packages/installer_repository
  jar_analyzer_repository:
    path: ./packages/jar_analyzer_repository
  java_duplicator_repository:
    path: ./packages/java_duplicator_repository
  java_info_repository:
    path: ./packages/java_info_repository
  java_printer_repository:
    path: ./packages/java_printer_repository
  launcher_repository:
    path: ./packages/launcher_repository
  locale_repository:
    path: ./packages/locale_repository
  network_repository:
    path: ./packages/network_repository
  picker_repository:
    path: ./packages/picker_repository
  process_cleaner_repository:
    path: ./packages/process_cleaner_repository
  server_management_repository:
    path: ./packages/server_management_repository
  server_properties_repository:
    path: ./packages/server_properties_repository
  server_repository:
    path: ./packages/server_repository
  system_repository:
    path: ./packages/system_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.0.0
  json_serializable: ^6.1.4
  mocktail: ^0.2.0
  dhttpd: ^4.0.0
  bloc_test: ^9.0.2

  build_version: ^2.0.0

  melos: 
    git: 
      url: https://github.com/Tokenyet/melos.git
      path: packages/melos


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_gen:
  output: lib/_gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - resources/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans/NotoSans-Regular.ttf
    - family: NotoSansTC
      fonts:
        - asset: fonts/NotoSansTC/NotoSansTC-Regular.otf
    - family: NotoSansSC
      fonts:
        - asset: fonts/NotoSansSC/NotoSansSC-Regular.otf
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
