name: vanilla_server_repository
description: A Dart Repository which fetching data from vanilla.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  path: ^1.8.0
  file: ^6.1.2
  platform: ^3.1.0
  process:
    git: 
      url: https://github.com/Tokenyet/process.dart.git
      ref: 9a9b873604a0c8f58d1419e160146885fd8392b6
  test_utilities:
    path: ../test_utilities
  dart_ipify: ^1.1.1
  dio: ^4.0.4
  validators: ^3.0.0
  cube_api:
    path: ../cube_api
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
